### ISSUE TITLE
Can't activate mods

### ISSUE THREAD

**Issue by DIXAK** [mkinfrared/baldurs-gate3-mod-manager#32]
Hi there!

I can't seem to get this to work for me. I have installed the mods, but I can't 'activate' them because there is no activation button showing up. I saw that there is an 'auto-activation' build in, but the mod does not seem to work for me. 
<img width="1018" alt="Schermafbeelding 2023-10-08 om 01 13 59" src="https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/147284669/e8c8b1a9-6748-4b82-8ab1-2cc282dc6d3b">

Still, thank you for creating this!

**Comment by mkinfrared** [comment]
If the mod doesn't have `info.json` file inside then there's no need to activate it. Like ModFixer for example. What activation button does is adding a node to ModOrder section of `modsettings.lsx`. To my first understanding I thought if the mod (I'm talking about a mod with `info.json` file) was not there then it wouldn't be active in the game, the idea was to activate/deactivate mod without uninstalling it. But as it turned out the mod would still load. I think I will get rid of `Activate/Deactivate` button and simply add new nodes to ModOrder upon installation, as it just confuses people

**Comment by DIXAK** [comment]
Thank you! Also figured out the mod I tried to use just does not work. I tried it on a Windows system and it still did not work. Might be the latest patch that causes problems. 

Closing this. Looking forward to use the Mac ModManager for all the other mods that hopefully will work!

**Comment by DIXAK** [comment]
One last little update, I got the Mod working on Windows. So after that I decided to copy my modsettings.lsx to my Mac setup, and it worked! Also, now I can actually ''deactivate'' the mod on Mac. 
<img width="1022" alt="Schermafbeelding_2023-10-08_om_16 53 00" src="https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/147284669/547f38fc-928f-4564-ad69-c9929c720b76">
