### ISSUE TITLE
No Activate button available

### ISSUE THREAD

**Issue by JayDub72** [mkinfrared/baldurs-gate3-mod-manager#51]
## Expected Behavior

I should be able to activate the mod after installing it within the tool.

## Current Behavior

Instead of letting me activate the mod, the app shows a blank section (no mod name) and a delete button only that does not do anything either.

## Steps to Reproduce

1. Open app
2. Select "Click this button to select files"
3. Browser to zip file of mod
4. Click open
5. Click "Install" in the right section under Modification Files to install the mod

<img width="890" alt="Install Icon" src="https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/31083720/20858973-62b9-4138-8ac1-493035d2c3e1">

<img width="890" alt="No Activiate Icon" src="https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/31083720/232859c7-08dd-474d-88b8-e9c1389f3108">

**Comment by finnetladebut** [comment]
I am having the same issue, reproducible with the same steps.

**Comment by mkinfrared** [comment]
I have just noticed that release notes were missing. I removed the activate/deactivate button as it didn't do what it was initially supposed to do. That button only added a node to `ModOrder` in modsettings and as I thought if you add a node there the mod would become active and removing it from there would make it obviously inactive. But as it turned out the game would still load the mod even if you remove it from `ModOrder`. To my understanding that section defines the load order of your installed mods, if applicable (presense of `info.json`). So I removed that button, the mods that you install from now on, if they have an `info.json` will update modsettings Mods and ModOrder.

**Comment by JayDub72** [comment]
Thanks @mkinfrared. Closing the issue.

**Comment by jiezheku** [comment]
Order is recessary.
for example, 'Stackable Items' MOD is must later then 'highlight everything', otherwise it does not work.
