### ISSUE TITLE
Need support for mods without json files

### ISSUE THREAD

**Issue by azwargamer** [mkinfrared/baldurs-gate3-mod-manager#70]
The manager correctly will copy the .pak file to the mods folder, but doe# not create an entry in the approximate files for loading the mods. This forces the user to have to manually find and edit these files resulting in errors. Create a generic process to create an entry when no provided .json file is included.

**Comment by Timodej** [comment]
Second this. An example for this would be the "bags bags bags" mod.

**Comment by mkinfrared** [comment]
I'm in the process of moving right now so not able to work on the app at the moment. But as soons as I'm done I will take a look if it's possible to add that feature.

**Comment by nmcclay** [comment]
I also encountered this issue, digging in a bit this is the bit that skips updating the `modsettings.lsx` for mods if there is no mod info:
https://github.com/mkinfrared/baldurs-gate3-mod-manager/blob/e64b727c77427cdb2b93ce095840e6afd0633c22/src/main/features/mod/installModsHandler/lib/helpers/addModsToSettings/addModsToSettings.ts#L25

Here is the line where the mod info is only populated via included JSON:

https://github.com/mkinfrared/baldurs-gate3-mod-manager/blob/e64b727c77427cdb2b93ce095840e6afd0633c22/src/main/entities/mod/lib/helpers/getModData/lib/getModDataFromArchive/getModDataFromArchive.ts#L37

My hunch would be simply populating mod info with pak data at this point will fall back pak data would fix this. I’ll setup my dev environment and try it when I get a chance.

**Comment by mkinfrared** [comment]
I had little time to investigate whether it's possible to get data from pak files. So here's an outcome. First all, pak files seem to contain same data provided in `info.json` so it can be used to populate the data for `modsettings.lsx`. And second, which is unfortunate, there's no lib for mac that can extract or read the contents of `pak` files for Divinity engine at the moment. The only working app which I found that managed to exract the pak files was [lslib](https://github.com/Norbyte/lslib). But it uses .Net Framework which is not cross platform. I will try to come up with a solution. If anyone knows a tool on mac which can extract pak files please let me know. That might help

**Comment by nmcclay** [comment]
I agree @mkinfrared the .pak contains all the needed details for this case but isn't available as toolkit outside of Windows. I was looking and found others discussing this problem with Linux based mod managers: https://github.com/CHollingworth/Lamp/issues/14

I hacked together a version of this mod manager working to create the expected JSON file, but I still needed to manually populate the necessary UUID/MD5/Folder/Version details in order to reliably get it to load. These details are somewhat visible in the .pak if you open it as a .txt file but ultimately not in reliably parsable way.

There are interesting ongoing projects to convert LsLib to [.NET 6](https://github.com/Norbyte/lslib/pull/139) (which may work with Mono) and another to allow it to work [standalone on Linux](https://github.com/Norbyte/lslib/pull/107). Unless anyone else is aware of any tools that can extract pak files those projects seem necessary to fix this issue reliably.

**Comment by mkinfrared** [comment]
I did some research, and fortunately it's seems to be doable at the moment. I will keep you updated

**Comment by nmcclay** [comment]
@mkinfrared can you clarify how PR #87 resolves this issue? Looking at the source I see some changes to how the UUID is generated but it is still not writing the details to the `modsettings.lsx` when there is no json file.

**Comment by mkinfrared** [comment]
Which mod are you trying to install? And which version of the app are you using?

**Comment by nmcclay** [comment]
@mkinfrared, my apologies. I simply missed clicking the activate button. This is an incredible fix, sorry for my confusion!
