### ISSUE TITLE
When I try to use the mod manager, there is no option to move it to mod order --

### ISSUE THREAD

**Issue by elisam34879** [mkinfrared/baldurs-gate3-mod-manager#77]
When I try to move the mods into mod order, it does not work. It is stuck on the mod inventory. How do I get this to work?

**Comment by mkinfrared** [comment]
I updated the app with support for `.pak` files, you can try to download the most recent version and see hot it goes. Hopefully it should fix your issue

**Comment by brightmoonjones** [comment]
thanks for you work on this. I'm having a similar issue. I downloaded the new version (which i think is the right one, i'm on an intel Mac and downloaded x64, not arm, and i see the activate button but it doesn't add anything to the mod order. it doesn't change anything at all. :( 

for some reason, since patch 4 released this morning the game overwrites the modsettings.lsx file as well. any help is greatly appreciated!

**Comment by mkinfrared** [comment]
thanks for the feedback and sorry to hear that. I haven't noticed that the game would overwrite the file, though I am using m1 arm. On activate click the mod should appear in the mod order section. I tested the new version with latest patch of the game, I successfully activated/deactivated astral dice mod and vemperens head. 

Is the game running when you try to add new mods with the app?

**Comment by LuxVesperis** [comment]
I've downloaded the new version (arm) and I also am having this issue. Clicking the activate button appears to do nothing & doesn't move any mods into the mod order. If I open the modsettings.lsx however I can see that it adds an entry for that mod every time the activate button is clicked. It just doesn't register as being activated for some reason.

**Comment by mkinfrared** [comment]
I justed checked on my machine, activation toggle works as expected. Can you provide your modsettings file and the mod you are trying to activate? I will investigate that issue

**Comment by LuxVesperis** [comment]
[modsettings.lsx.zip](https://github.com/mkinfrared/baldurs-gate3-mod-manager/files/13252950/modsettings.lsx.zip)
Here's my modsettings. I've used the previous version of your mod manager as well as manual install. 

The only thing that's not working for me is the mod order/activate. The mods still work in the game as expected and the installation of mods (including paks, which I tested) is also working.

The difference seems to be that installing the mod now doesn't automatically add the mod into the modsettings file as it did with the previous version. It's only added after clicking activate (which I assume is intentional). It just seems that the app doesn't recognise what's already been activated or what exists in the modsettings file already.

I did clear my mods and start with a fresh modsettings file to see if that made a difference but I got the same behaviour.

**Comment by moniquemolina2002** [comment]
I have the same thing, I can't activate or move things

**Comment by mkinfrared** [comment]
> The difference seems to be that installing the mod now doesn't automatically add the mod into the modsettings file as it did with the previous version. It's only added after clicking activate (which I assume is intentional).

Yes you are correct. Now that the app can read data directly from `pak` files, it determines the installed mods based on the files you have in your `Mods` directory. It will not modify the `modsettings` file on installation, only on activation the app will update the modsettings with required data. This is done so you could disable the mod without deleting it from the system

**Comment by LuxVesperis** [comment]
> > The difference seems to be that installing the mod now doesn't automatically add the mod into the modsettings file as it did with the previous version. It's only added after clicking activate (which I assume is intentional).
> 
> Yes you are correct. Now that the app can read data directly from `pak` files, it determines the installed mods based on the files you have in your `Mods` directory. It will not modify the `modsettings` file on installation, only on activation the app will update the modsettings with required data. This is done so you could disable the mod without deleting it from the system

Yes, totally fair. So the issue seems to be activation doesn't add the mod to the mod order, and doesn't switch to 'deactivate' after clicking it. Currently I can click 'activate' several times and it will add several instances to modsettings without registering that it's active within the app.

**Comment by mkinfrared** [comment]
I managed to reproduce the bug with your modsettings. Which is good! What I can see is that your modsettings is missing children tag in ModOrder for some reason. You can manually add that to your modsettings and it should fix your problem.

From
`<node id="ModOrder" />`

To
`<node id="ModOrder">
	<children> </children>
</node>`

That should fix your problem.

I will try to come up with a solution for such a case. Thank again for provided file.

**Comment by LuxVesperis** [comment]
Ah okay! Thank you for your help troubleshooting. Everything seems to be working as it should now.

**Comment by mkinfrared** [comment]
I will release an update with a fix for that

**Comment by moniquemolina2002** [comment]
THANK YOU!!!! You have been the only reason I can play with mods, you're the best. Question- do I redownload the mods all my mods? or is it ok to just download the new version (im hoping i can get astarion's earrings mod to work now)? I just hate having to find and download the zip files form nexus again so Im trying to avoid it.

**Comment by LuxVesperis** [comment]
> THANK YOU!!!! You have been the only reason I can play with mods, you're the best. Question- do I redownload the mods all my mods? or is it ok to just download the new version (im hoping i can get astarion's earrings mod to work now)? I just hate having to find and download the zip files form nexus again so Im trying to avoid it.

You can safely use newer versions of the mod manager without having to redownload all your mods. Keep in mind that Patch 4 has just dropped which may have broken some mods, so some things you have downloaded may need updates to work properly.
